#!/usr/bin/env bash

db_host=localhost
db_port=5432
db_user=postgres
db_name=lbtest
db_pass=password
http_port=7645


echo "BUILDING"
echo "--------"
cabal new-build

rc=$?
if (( rc != 0 )); then
    echo "Failed to build"
    exit $rc
fi

echo ""
echo "RUNNING"
echo "-------"
# Make sure we're running the intended version -- nix defaults to 802 on my setup
exe=$(find dist-newstyle -type f -executable -wholename "*ghc-8.0.2*leaderboard")
DBPASS="$db_pass" "$exe" --db_host="$db_host" --db_port="$db_port" --db_user="$db_user" --db_name="$db_name" --port=7645 $@
